// examples/taro_vue2/src/pages/font/index.vue
<script>
import FontSize from './components/FontSize.vue'
import FontBold from './components/FontBold.vue'
import LetterSpacing from './components/LetterSpacing.vue'
import LineHeight from './components/LineHeight.vue'
import TextAlign from './components/TextAlign.vue'
import TextColor from './components/TextColor.vue'
import TextDecoration from './components/TextDecoration.vue'
import TextDecorationStyle from './components/TextDecorationStyle.vue'
import TextIndent from './components/TextIndent.vue'
import TextOpacity from './components/TextOpacity.vue'
import TextShadow from './components/TextShadow.vue'

export default {
  components: {
    FontSize,
    FontBold,
    LetterSpacing,
    LineHeight,
    TextAlign,
    TextColor,
    TextDecoration,
    TextDecorationStyle,
    TextIndent,
    TextOpacity,
    TextShadow,
  },
}
</script>

<template>
  <view>
    <FontSize />
    <FontBold />
    <LetterSpacing />
    <LineHeight />
    <TextAlign />
    <TextColor />
    <TextDecoration />
    <TextDecorationStyle />
    <TextIndent />
    <TextOpacity />
    <TextShadow />
  </view>
</template>

// examples/taro_react/src/pages/font/index.tsx
import {View} from '@tarojs/components'
import FontSize from './components/FontSize'
import FontBold from './components/FontBold'
import LetterSpacing from './components/LetterSpacing'
import LineHeight from './components/LineHeight'
import TextAlign from './components/TextAlign'
import TextColor from './components/TextColor'
import TextDecoration from './components/TextDecoration'
import TextDecorationStyle from './components/TextDecorationStyle'
import TextIndent from './components/TextIndent'
import TextOpacity from './components/TextOpacity'
import TextShadow from './components/TextShadow'



export default function() {
  return (
    <View>
    <FontSize />
    <FontBold />
    <LetterSpacing />
    <LineHeight />
    <TextAlign />
    <TextColor />
    <TextDecoration />
    <TextDecorationStyle />
    <TextIndent />
    <TextOpacity />
    <TextShadow />
  </View>
  )
}
