// examples/taro_vue3/src/pages/shadow/index.vue
<template>
  <view>
    <view class="p-2 bg-gray-100">
      <view class="text-2xl text-center my-3">
        shadow
      </view>
      <view class="h-200 mb3 bg-white center shadow-none">
        shadow-none
      </view>

      <view class="h-200 mb3 bg-white center shadow">
        shadow
      </view>

      <view class="h-200 mb3 bg-white center shadow-sm">
        shadow-sm
      </view>

      <view class="h-200 mb3 bg-white center shadow-md">
        shadow-md
      </view>

      <view class="h-200 mb3 bg-white center shadow-lg">
        shadow-lg
      </view>

      <view class="h-200 mb3 bg-white center shadow-xl">
        shadow-xl
      </view>

      <view class="h-200 mb3 bg-white center shadow-2xl">
        shadow-2xl
      </view>

      <view class="h-200 mb3 bg-white center shadow-inner">
        shadow-inner
      </view>
    </view>
  </view>
</template>

// examples/taro_webpack5_react/src/pages/shadow/index.tsx
import {View} from '@tarojs/components'

export default function() {
  return (
    <View>
    <View className='p-2 bg-gray-100'>
      <View className='text-2xl text-center my-3'>
        shadow
      </View>
      <View className='h-200 mb3 bg-white center shadow-none'>
        shadow-none
      </View>

      <View className='h-200 mb3 bg-white center shadow'>
        shadow
      </View>

      <View className='h-200 mb3 bg-white center shadow-sm'>
        shadow-sm
      </View>

      <View className='h-200 mb3 bg-white center shadow-md'>
        shadow-md
      </View>

      <View className='h-200 mb3 bg-white center shadow-lg'>
        shadow-lg
      </View>

      <View className='h-200 mb3 bg-white center shadow-xl'>
        shadow-xl
      </View>

      <View className='h-200 mb3 bg-white center shadow-2xl'>
        shadow-2xl
      </View>

      <View className='h-200 mb3 bg-white center shadow-inner'>
        shadow-inner
      </View>
    </View>
  </View>
  )
}
