// examples/taro_react/src/pages/font/components/TextColor.tsx


export default function TextColor() {
  return (
    <view className='p-2'>
    <view className='text-2xl text-center my-3'>
      text-color
    </view>

    <view className='text-transparent'>
      text-transparent
    </view>

    <view className='text-gray-500'>
      text-gray-500
    </view>

    <view className='text-red-500'>
      text-red-500
    </view>

    <view className='text-yellow-500'>
      text-yellow-500
    </view>

    <view className='text-blue-500'>
      text-blue-500
    </view>

    <view className='text-green-500'>
      text-green-500
    </view>

    <view className='text-gray-500_50'>
      text-gray-500_50
    </view>

    <view className='text-gray-500:50'>
      text-gray-500:50
    </view>

    <view className='text-gray-500/50'>
      text-gray-500/50
    </view>

    <view className='text-red-500_50'>
      text-red-500_50
    </view>

    <view className='text-red-500:50'>
      text-red-500:50
    </view>

    <view className='text-red-500/50'>
      text-red-500/50
    </view>

    <view className='text-yellow-500_50'>
      text-yellow-500_50
    </view>

    <view className='text-yellow-500:50'>
      text-yellow-500:50
    </view>

    <view className='text-yellow-500/50'>
      text-yellow-500/50
    </view>

    <view className='text-blue-500_50'>
      text-blue-500_50
    </view>

    <view className='text-blue-500/50'>
      text-blue-500/50
    </view>

    <view className='text-blue-500:50'>
      text-blue-500:50
    </view>

    <view className='text-green-500_50'>
      text-green-500_50
    </view>

    <view className='text-green-500:50'>
      text-green-500:50
    </view>

    <view className='text-green-500/50'>
      text-green-500/50
    </view>

    <view className='c-hex-157_60'>
      c-hex-157_60
    </view>

    <view className='c-hex-157/60'>
      c-hex-157/60
    </view>

    <view className='c-[#157]/60'>
      c-[#157]/60
    </view>

    <view className='c-[#157]_60'>
      c-[#157]_60
    </view>

    <view className='c-[#157]:60'>
      c-[#157]:60
    </view>

    <view className='c-[#784469]:60 bg-[#153625]/60'>
    #784469 #153625
    </view>
  </view>
  )
}

// examples/uniapp_vue3/src/pages/font/components/TextColor.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      text-color
    </view>

    <view class="text-transparent">
      text-transparent
    </view>

    <view class="text-gray-500">
      text-gray-500
    </view>

    <view class="text-red-500">
      text-red-500
    </view>

    <view class="text-yellow-500">
      text-yellow-500
    </view>

    <view class="text-blue-500">
      text-blue-500
    </view>

    <view class="text-green-500">
      text-green-500
    </view>

    <view class="text-gray-500_50">
      text-gray-500_50
    </view>

    <view class="text-gray-500:50">
      text-gray-500:50
    </view>

    <view class="text-gray-500/50">
      text-gray-500/50
    </view>

    <view class="text-red-500_50">
      text-red-500_50
    </view>

    <view class="text-red-500:50">
      text-red-500:50
    </view>

    <view class="text-red-500/50">
      text-red-500/50
    </view>

    <view class="text-yellow-500_50">
      text-yellow-500_50
    </view>

    <view class="text-yellow-500:50">
      text-yellow-500:50
    </view>

    <view class="text-yellow-500/50">
      text-yellow-500/50
    </view>

    <view class="text-blue-500_50">
      text-blue-500_50
    </view>

    <view class="text-blue-500/50">
      text-blue-500/50
    </view>

    <view class="text-blue-500:50">
      text-blue-500:50
    </view>

    <view class="text-green-500_50">
      text-green-500_50
    </view>

    <view class="text-green-500:50">
      text-green-500:50
    </view>

    <view class="text-green-500/50">
      text-green-500/50
    </view>

    <view class="c-hex-157_60">
      c-hex-157_60
    </view>

    <view class="c-hex-157/60">
      c-hex-157/60
    </view>

    <view class="c-[#157]/60">
      c-[#157]/60
    </view>

    <view class="c-[#157]_60">
      c-[#157]_60
    </view>

    <view class="c-[#157]:60">
      c-[#157]:60
    </view>

    <view class="c-[#196]/50">
      c-[#198]
    </view>
  </view>
</template>
