// examples/taro_webpack5_react/src/pages/font/components/TextAlign.tsx
import {View} from '@tarojs/components'

export default function TextAlign() {
  return (
    <View className='p-2'>
    <View className='text-2xl text-center my-3'>
      text-align
    </View>

    <View className='text-left'>
      text-left
    </View>

    <View className='text-center'>
      text-center
    </View>

    <View className='text-right'>
      text-right
    </View>
  </View>
  )
}

// examples/uniapp_vue3/src/pages/font/components/TextAlign.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      text-align
    </view>

    <view class="text-left">
      text-left
    </view>

    <view class="text-center">
      text-center
    </view>

    <view class="text-right">
      text-right
    </view>
  </view>
</template>
