// examples/taro_react/src/pages/font/components/LetterSpacing.tsx



export default function LetterSpacing() {
  return (
    <view className='p-2'>
    <view className='text-2xl text-center my-3'>
      letter-spacing
    </view>
    <view className='tracking-tighter'>
      tracking-tighter
    </view>

    <view className='tracking-tight'>
      tracking-tight
    </view>

    <view className='tracking-normal'>
      tracking-normal
    </view>

    <view className='tracking-wide'>
      tracking-wide
    </view>

    <view className='tracking-wider'>
      tracking-wider
    </view>

    <view className='tracking-widest'>
      tracking-widest
    </view>

    <view className='tracking-5px'>
      tracking-5px
    </view>

    <view className='tracking-5rpx'>
      tracking-5rpx
    </view>
  </view>
  )
}

// examples/taro_vue2/src/pages/font/components/LetterSpacing.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      letter-spacing
    </view>
    <view class="tracking-tighter">
      tracking-tighter
    </view>

    <view class="tracking-tight">
      tracking-tight
    </view>

    <view class="tracking-normal">
      tracking-normal
    </view>

    <view class="tracking-wide">
      tracking-wide
    </view>

    <view class="tracking-wider">
      tracking-wider
    </view>

    <view class="tracking-widest">
      tracking-widest
    </view>

    <view class="tracking-5px">
      tracking-5px
    </view>

    <view class="tracking-5rpx">
      tracking-5rpx
    </view>
  </view>
</template>
