// examples/taro_webpack5_react/src/pages/font/components/TextColor.tsx
import {View} from '@tarojs/components'

export default function TextColor() {
  return (
    <View className='p-2'>
    <View className='text-2xl text-center my-3'>
      text-color
    </View>

    <View className='text-transparent'>
      text-transparent
    </View>

    <View className='text-gray-500'>
      text-gray-500
    </View>

    <View className='text-red-500'>
      text-red-500
    </View>

    <View className='text-yellow-500'>
      text-yellow-500
    </View>

    <View className='text-blue-500'>
      text-blue-500
    </View>

    <View className='text-green-500'>
      text-green-500
    </View>

    <View className='text-gray-500_50'>
      text-gray-500_50
    </View>

    <View className='text-gray-500:50'>
      text-gray-500:50
    </View>

    <View className='text-gray-500/50'>
      text-gray-500/50
    </View>

    <View className='text-red-500_50'>
      text-red-500_50
    </View>

    <View className='text-red-500:50'>
      text-red-500:50
    </View>

    <View className='text-red-500/50'>
      text-red-500/50
    </View>

    <View className='text-yellow-500_50'>
      text-yellow-500_50
    </View>

    <View className='text-yellow-500:50'>
      text-yellow-500:50
    </View>

    <View className='text-yellow-500/50'>
      text-yellow-500/50
    </View>

    <View className='text-blue-500_50'>
      text-blue-500_50
    </View>

    <View className='text-blue-500/50'>
      text-blue-500/50
    </View>

    <View className='text-blue-500:50'>
      text-blue-500:50
    </View>

    <View className='text-green-500_50'>
      text-green-500_50
    </View>

    <View className='text-green-500:50'>
      text-green-500:50
    </View>

    <View className='text-green-500/50'>
      text-green-500/50
    </View>

    <View className='c-hex-157_60'>
      c-hex-157_60
    </View>

    <View className='c-hex-157/60'>
      c-hex-157/60
    </View>

    <View className='c-[#157]/60'>
      c-[#157]/60
    </View>

    <View className='c-[#157]_60'>
      c-[#157]_60
    </View>

    <View className='c-[#157]:60'>
      c-[#157]:60
    </View>

    <View className='c-[#78dd]:90 bg-[#153]:40'>
    #784469 #153625
    </View>
  </View>
  )
}

// examples/taro_vue2/src/pages/font/components/TextColor.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      text-color
    </view>

    <view class="text-transparent">
      text-transparent
    </view>

    <view class="text-gray-500">
      text-gray-500
    </view>

    <view class="text-red-500">
      text-red-500
    </view>

    <view class="text-yellow-500">
      text-yellow-500
    </view>

    <view class="text-blue-500">
      text-blue-500
    </view>

    <view class="text-green-500">
      text-green-500
    </view>

    <view class="text-gray-500_50">
      text-gray-500_50
    </view>

    <view class="text-gray-500:50">
      text-gray-500:50
    </view>

    <view class="text-gray-500/50">
      text-gray-500/50
    </view>

    <view class="text-red-500_50">
      text-red-500_50
    </view>

    <view class="text-red-500:50">
      text-red-500:50
    </view>

    <view class="text-red-500/50">
      text-red-500/50
    </view>

    <view class="text-yellow-500_50">
      text-yellow-500_50
    </view>

    <view class="text-yellow-500:50">
      text-yellow-500:50
    </view>

    <view class="text-yellow-500/50">
      text-yellow-500/50
    </view>

    <view class="text-blue-500_50">
      text-blue-500_50
    </view>

    <view class="text-blue-500/50">
      text-blue-500/50
    </view>

    <view class="text-blue-500:50">
      text-blue-500:50
    </view>

    <view class="text-green-500_50">
      text-green-500_50
    </view>

    <view class="text-green-500:50">
      text-green-500:50
    </view>

    <view class="text-green-500/50">
      text-green-500/50
    </view>

    <view class="c-hex-157_60">
      c-hex-157_60
    </view>

    <view class="c-hex-157/60">
      c-hex-157/60
    </view>

    <view class="c-[#157]/60">
      c-[#157]/60
    </view>

    <view class="c-[#157]_60">
      c-[#157]_60
    </view>

    <view class="c-[#157]:60">
      c-[#157]:60
    </view>

    <view class="c-[#157111]:60">
      #157111
    </view>

     <view class="c-[#157111]:80">
      #157111
    </view>
  </view>
</template>
