// examples/taro_react/src/pages/border/components/BorderColor.tsx


export default function BorderColor() {
  return (
    <view className='p-2'>
    <view className='text-2xl text-center my-3'>
      border-color
    </view>
    <view className='flex flex-col items-center'>
      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-transparent border-4'>
        border-transparent border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-gray-500 border-4'>
        border-gray-500 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-red-500 border-4'>
        border-red-500 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-yellow-500 border-4'>
        border-yellow-500 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-blue-500 border-4'>
        border-blue-500 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-green-500 border-4'>
        border-green-500 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-gray-500_20 border-4'>
        border-gray-500_20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-gray-500/20 border-4'>
        border-gray-500/20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-gray-500:20 border-4'>
        border-gray-500:20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-red-500_20 border-4'>
        border-red-500_20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-red-500/20 border-4'>
        border-red-500/20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-red-500:20 border-4'>
        border-red-500:20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-yellow-500_20 border-4'>
        border-yellow-500_20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-yellow-500/20 border-4'>
        border-yellow-500/20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-yellow-500:20 border-4'>
        border-yellow-500:20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-blue-500_20 border-4'>
        border-blue-500_20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-blue-500/20 border-4'>
        border-blue-500/20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-blue-500:20 border-4'>
        border-blue-500:20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-green-500_20 border-4'>
        border-green-500_20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-green-500/20 border-4'>
        border-green-500/20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-green-500:20 border-4'>
        border-green-500:20 border-4
      </view>

      <view className='w-half h-200 mb-3  bg-blue-100 center text-center border-[#db2777]:20 border-4'>
        #db2777:20 border-4
      </view>
    </view>
  </view>
  )
}

// examples/taro_vue3/src/pages/border/components/BorderColor.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      border-color
    </view>
    <view class="flex flex-col items-center">
      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-transparent border-4">
        border-transparent border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-gray-500 border-4">
        border-gray-500 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-red-500 border-4">
        border-red-500 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-yellow-500 border-4">
        border-yellow-500 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-blue-500 border-4">
        border-blue-500 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-green-500 border-4">
        border-green-500 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-gray-500_20 border-4">
        border-gray-500_20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-gray-500/20 border-4">
        border-gray-500/20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-gray-500:20 border-4">
        border-gray-500:20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-red-500_20 border-4">
        border-red-500_20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-red-500/20 border-4">
        border-red-500/20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-red-500:20 border-4">
        border-red-500:20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-yellow-500_20 border-4">
        border-yellow-500_20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-yellow-500/20 border-4">
        border-yellow-500/20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-yellow-500:20 border-4">
        border-yellow-500:20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-blue-500_20 border-4">
        border-blue-500_20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-blue-500/20 border-4">
        border-blue-500/20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-blue-500:20 border-4">
        border-blue-500:20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-green-500_20 border-4">
        border-green-500_20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-green-500/20 border-4">
        border-green-500/20 border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-green-500:20 border-4">
        border-green-500:20 border-4
      </view>
    </view>
  </view>
</template>
