// examples/taro_webpack5_react/src/pages/font/components/FontSize.tsx
import {View} from '@tarojs/components'

export default function FontSize() {
  return (
    <View className='p-2'>
    <View className='text-2xl text-center my-3'>
      font-size
    </View>
    <View className='text-xs'>
      text-xs
    </View>
    <View className='text-sm'>
      text-sm
    </View>
    <View className='text-base'>
      text-base
    </View>
    <View className='text-lg'>
      text-lg
    </View>
    <View className='text-40'>
      text-40
    </View>
    <View className='text-xl'>
      text-xl
    </View>
    <View className='text-2xl'>
      text-2xl
    </View>
    <View className='text-3xl'>
      text-3xl
    </View>
    <View className='text-4xl'>
      text-4xl
    </View>
    <View className='text-5xl'>
      text-5xl
    </View>
    <View className='text-6xl'>
      text-6xl
    </View>
    <View className='text-7xl'>
      text-7xl
    </View>
    <View className='text-8xl'>
      text-8xl
    </View>
  </View>
)}

// examples/taro_webpack5_vue3/src/pages/font/components/FontSize.vue
<template>
  <view class="p-2">
    <view
      class="text-2xl text-center my-3"
    >
      font-size
    </view>
    <view class="text-xs">
      text-xs
    </view>
    <view class="text-sm">
      text-sm
    </view>
    <view class="text-base">
      text-base
    </view>
    <view class="text-lg">
      text-lg
    </view>
    <view class="text-40">
      text-40
    </view>
    <view class="text-xl">
      text-xl
    </view>
    <view class="text-2xl">
      text-2xl
    </view>
    <view class="text-3xl">
      text-3xl
    </view>
    <view class="text-4xl">
      text-4xl
    </view>
    <view class="text-5xl">
      text-5xl
    </view>
    <view class="text-6xl">
      text-6xl
    </view>
    <view class="text-7xl">
      text-7xl
    </view>
    <view class="text-8xl">
      text-8xl
    </view>
  </view>
</template>
