// examples/taro_webpack5_vue3/src/pages/font/components/FontSize.vue
<template>
  <view class="p-2">
    <view
      class="text-2xl text-center my-3"
    >
      font-size
    </view>
    <view class="text-xs">
      text-xs
    </view>
    <view class="text-sm">
      text-sm
    </view>
    <view class="text-base">
      text-base
    </view>
    <view class="text-lg">
      text-lg
    </view>
    <view class="text-40">
      text-40
    </view>
    <view class="text-xl">
      text-xl
    </view>
    <view class="text-2xl">
      text-2xl
    </view>
    <view class="text-3xl">
      text-3xl
    </view>
    <view class="text-4xl">
      text-4xl
    </view>
    <view class="text-5xl">
      text-5xl
    </view>
    <view class="text-6xl">
      text-6xl
    </view>
    <view class="text-7xl">
      text-7xl
    </view>
    <view class="text-8xl">
      text-8xl
    </view>
  </view>
</template>

// examples/taro_react/src/pages/font/components/FontSize.tsx
export default function FontSize() {
  return (
    <view className='p-2'>
    <view className='text-2xl text-center my-3'>
      font-size
    </view>
    <view className='text-xs'>
      text-xs
    </view>
    <view className='text-sm'>
      text-sm
    </view>
    <view className='text-base'>
      text-base
    </view>
    <view className='text-lg'>
      text-lg
    </view>
    <view className='text-40'>
      text-40
    </view>
    <view className='text-xl'>
      text-xl
    </view>
    <view className='text-2xl'>
      text-2xl
    </view>
    <view className='text-3xl'>
      text-3xl
    </view>
    <view className='text-4xl'>
      text-4xl
    </view>
    <view className='text-5xl'>
      text-5xl
    </view>
    <view className='text-6xl'>
      text-6xl
    </view>
    <view className='text-7xl'>
      text-7xl
    </view>
    <view className='text-8xl'>
      text-8xl
    </view>
  </view>
)}
