// examples/taro4_vite_vue3/src/pages/font/components/FontBold.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      font-bold
    </view>
    <view class="font-thin">
      font-thin
    </view>

    <view class="font-extralight">
      font-extralight
    </view>

    <view class="font-light">
      font-light
    </view>

    <view class="font-normal">
      font-normal
    </view>

    <view class="font-medium">
      font-medium
    </view>

    <view class="font-semibold">
      font-semibold
    </view>

    <view class="font-bold">
      font-bold
    </view>

    <view class="font-extrabold">
      font-extrabold
    </view>

    <view class="font-black">
      font-black
    </view>

    <view class="font-400">
      font-400
    </view>

    <view class="font-600">
      font-600
    </view>
  </view>
</template>

// examples/taro_react/src/pages/font/components/FontBold.tsx
export default function FontBold() {
  return (
    <view className='p-2'>
    <view className='text-2xl text-center my-3'>
      font-bold
    </view>
    <view className='font-thin'>
      font-thin
    </view>

    <view className='font-extralight'>
      font-extralight
    </view>

    <view className='font-light'>
      font-light
    </view>

    <view className='font-normal'>
      font-normal
    </view>

    <view className='font-medium'>
      font-medium
    </view>

    <view className='font-semibold'>
      font-semibold
    </view>

    <view className='font-bold'>
      font-bold
    </view>

    <view className='font-extrabold'>
      font-extrabold
    </view>

    <view className='font-black'>
      font-black
    </view>

    <view className='font-400'>
      font-400
    </view>

    <view className='font-600'>
      font-600
    </view>
  </view>
  )
}
