// examples/uniapp_vue3/src/pages/font/components/TextAlign.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      text-align
    </view>

    <view class="text-left">
      text-left
    </view>

    <view class="text-center">
      text-center
    </view>

    <view class="text-right">
      text-right
    </view>
  </view>
</template>

// examples/taro_react/src/pages/font/components/TextAlign.tsx


export default function TextAlign() {
  return (
    <view className='p-2'>
    <view className='text-2xl text-center my-3'>
      text-align
    </view>

    <view className='text-left'>
      text-left
    </view>

    <view className='text-center'>
      text-center
    </view>

    <view className='text-right'>
      text-right
    </view>
  </view>
  )
}
