// examples/taro_webpack4_vue3/src/pages/font/components/TextIndent.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      text-indent
    </view>

    <view class="indent">
      indent
    </view>

    <view class="indent-2em">
      indent-2em
    </view>

    <view class="indent-32rpx">
      indent-32rpx
    </view>

    <view class="indent-xs">
      indent-xs
    </view>

    <view class="indent-sm">
      indent-sm
    </view>

    <view class="indent-md">
      indent-md
    </view>

    <view class="indent-lg">
      indent-lg
    </view>

    <view class="indent-xl">
      indent-xl
    </view>

    <view class="indent-2xl">
      indent-2xl
    </view>

    <view class="indent-3xl">
      indent-3xl
    </view>

    <view class="-indent-xs">
      -indent-xs
    </view>

    <view class="-indent-5rpx">
      -indent-5rpx
    </view>
  </view>
</template>

// examples/taro_react/src/pages/font/components/TextIndent.tsx


export default function TextIndent() {
  return (
    <view className='p-2'>
    <view className='text-2xl text-center my-3'>
      text-indent
    </view>

    <view className='indent'>
      indent
    </view>

    <view className='indent-2em'>
      indent-2em
    </view>

    <view className='indent-32rpx'>
      indent-32rpx
    </view>

    <view className='indent-xs'>
      indent-xs
    </view>

    <view className='indent-sm'>
      indent-sm
    </view>

    <view className='indent-md'>
      indent-md
    </view>

    <view className='indent-lg'>
      indent-lg
    </view>

    <view className='indent-xl'>
      indent-xl
    </view>

    <view className='indent-2xl'>
      indent-2xl
    </view>

    <view className='indent-3xl'>
      indent-3xl
    </view>

    <view className='-indent-xs'>
      -indent-xs
    </view>

    <view className='-indent-5rpx'>
      -indent-5rpx
    </view>
  </view>
  )
}
