// examples/taro_vue2/src/pages/shadow/index.vue
<template>
  <view>
    <view class="p-2 bg-gray-100">
      <view class="text-2xl text-center my-3">
        shadow
      </view>
      <view class="h-200 mb3 bg-white center shadow-none">
        shadow-none
      </view>

      <view class="h-200 mb3 bg-white center shadow">
        shadow
      </view>

      <view class="h-200 mb3 bg-white center shadow-sm">
        shadow-sm
      </view>

      <view class="h-200 mb3 bg-white center shadow-md">
        shadow-md
      </view>

      <view class="h-200 mb3 bg-white center shadow-lg">
        shadow-lg
      </view>

      <view class="h-200 mb3 bg-white center shadow-xl">
        shadow-xl
      </view>

      <view class="h-200 mb3 bg-white center shadow-2xl">
        shadow-2xl
      </view>

      <view class="h-200 mb3 bg-white center shadow-inner">
        shadow-inner
      </view>

      <view class="h-200 mb3 bg-white center shadow-[0px_4px_4px_0px_rgba(237,_0,_0,_1)]">
        [0px_4px_4px_0px_rgba(237,_0,_0,_1)]
      </view>
    </view>
  </view>
</template>

// examples/taro_react/src/pages/shadow/index.tsx


export default function() {
  return (
    <view>
    <view className='p-2 bg-gray-100'>
      <view className='text-2xl text-center my-3'>
        shadow
      </view>
      <view className='h-200 mb3 bg-white center shadow-none'>
        shadow-none
      </view>

      <view className='h-200 mb3 bg-white center shadow'>
        shadow
      </view>

      <view className='h-200 mb3 bg-white center shadow-sm'>
        shadow-sm
      </view>

      <view className='h-200 mb3 bg-white center shadow-md'>
        shadow-md
      </view>

      <view className='h-200 mb3 bg-white center shadow-lg'>
        shadow-lg
      </view>

      <view className='h-200 mb3 bg-white center shadow-xl'>
        shadow-xl
      </view>

      <view className='h-200 mb3 bg-white center shadow-2xl'>
        shadow-2xl
      </view>

      <view className='h-200 mb3 bg-white center shadow-inner'>
        shadow-inner
      </view>
    </view>
  </view>
  )
}
