// examples/taro_react/src/pages/border/index.tsx

import BorderRadius from './components/BorderRadius'
import BorderWidth from './components/BorderWidth'
import BorderStyle from './components/BorderStyle'
import BorderColor from './components/BorderColor'

export default function() {
  return (
    <view className='bg-white'>
    <BorderRadius />
    <BorderWidth />
    <BorderStyle />
    <BorderColor />
  </view>
  )
}

// examples/uniapp_vue2/src/pages/border/index.vue
<script>
import BorderRadius from './components/BorderRadius.vue'
import BorderWidth from './components/BorderWidth.vue'
import BorderStyle from './components/BorderStyle.vue'
import BorderColor from './components/BorderColor.vue'
export default {
  components: {
    BorderRadius,
    BorderWidth,
    BorderStyle,
    BorderColor,
  },
}
</script>

<template>
  <view class="bg-white">
    <BorderRadius />
    <BorderWidth />
    <BorderStyle />
    <BorderColor />
  </view>
</template>
