// examples/taro_webpack5_react/src/pages/font/components/TextDecoration.tsx
import {View} from '@tarojs/components'

export default function TextDecoration() {
  return (
    <View className='p-2'>
    <View className='text-2xl text-center my-3'>
      text-decoration
    </View>

    <View className='overline'>
      overline
    </View>

    <View className='underline'>
      underline
    </View>

    <View className='line-through'>
      line-through
    </View>

    <View className='no-underline'>
      no-underline
    </View>

    <View className='decoration-solid'>
      decoration-solid
    </View>
  </View>
  )
}

// examples/taro_vue3/src/pages/font/components/TextDecoration.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      text-decoration
    </view>

    <view class="overline">
      overline
    </view>

    <view class="underline">
      underline
    </view>

    <view class="line-through">
      line-through
    </view>

    <view class="no-underline">
      no-underline
    </view>

    <view class="decoration-solid">
      decoration-solid
    </view>
  </view>
</template>
