// examples/taro_react/src/pages/font/components/TextDecoration.tsx


export default function TextDecoration() {
  return (
    <view className='p-2'>
    <view className='text-2xl text-center my-3'>
      text-decoration
    </view>

    <view className='overline'>
      overline
    </view>

    <view className='underline'>
      underline
    </view>

    <view className='line-through'>
      line-through
    </view>

    <view className='no-underline'>
      no-underline
    </view>

    <view className='decoration-solid'>
      decoration-solid
    </view>
  </view>
  )
}

// examples/taro_vue3/src/pages/font/components/TextDecoration.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      text-decoration
    </view>

    <view class="overline">
      overline
    </view>

    <view class="underline">
      underline
    </view>

    <view class="line-through">
      line-through
    </view>

    <view class="no-underline">
      no-underline
    </view>

    <view class="decoration-solid">
      decoration-solid
    </view>
  </view>
</template>
