// examples/taro_webpack4_vue3/src/pages/font/components/LineHeight.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      line-height
    </view>

    <view class="leading-none">
      leading-none
    </view>

    <view class="leading-tight">
      leading-tight
    </view>

    <view class="leading-snug">
      leading-snug
    </view>

    <view class="leading-normal">
      leading-normal
    </view>

    <view class="leading-relaxed">
      leading-relaxed
    </view>

    <view class="leading-loose">
      leading-loose
    </view>
  </view>
</template>

// examples/taro_webpack5_react/src/pages/font/components/LineHeight.tsx
import {View} from '@tarojs/components'

export default function LineHeight() {
  return (
    <View className='p-2'>
    <View className='text-2xl text-center my-3'>
      line-height
    </View>

    <View className='leading-none'>
      leading-none
    </View>

    <View className='leading-tight'>
      leading-tight
    </View>

    <View className='leading-snug'>
      leading-snug
    </View>

    <View className='leading-normal'>
      leading-normal
    </View>

    <View className='leading-relaxed'>
      leading-relaxed
    </View>

    <View className='leading-loose'>
      leading-loose
    </View>
  </View>
  )
}
