// examples/taro_vue2/src/pages/font/components/TextOpacity.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      text-opacity
    </view>

    <view class="text-black text-opacity-0">
      text-opacity-0
    </view>

    <view class="text-black text-opacity-5">
      text-opacity-5
    </view>

    <view class="text-black text-opacity-10">
      text-opacity-10
    </view>

    <view class="text-black text-opacity-20">
      text-opacity-20
    </view>

    <view class="text-black text-opacity-30">
      text-opacity-30
    </view>

    <view class="text-black text-opacity-40">
      text-opacity-40
    </view>

    <view class="text-black text-opacity-50">
      text-opacity-50
    </view>

    <view class="text-black text-opacity-60">
      text-opacity-60
    </view>

    <view class="text-black text-opacity-70">
      text-opacity-70
    </view>

    <view class="text-black text-opacity-80">
      text-opacity-80
    </view>

    <view class="text-black text-opacity-90">
      text-opacity-90
    </view>

    <view class="text-black text-opacity-100">
      text-opacity-100
    </view>
  </view>
</template>

// examples/taro_webpack5_react/src/pages/font/components/TextOpacity.tsx

import {View} from '@tarojs/components'

export default function TextOpacity() {
  return (
    <View className='p-2'>
    <View className='text-2xl text-center my-3'>
      text-opacity
    </View>

    <View className='text-black text-opacity-0'>
      text-opacity-0
    </View>

    <View className='text-black text-opacity-5'>
      text-opacity-5
    </View>

    <View className='text-black text-opacity-10'>
      text-opacity-10
    </View>

    <View className='text-black text-opacity-20'>
      text-opacity-20
    </View>

    <View className='text-black text-opacity-30'>
      text-opacity-30
    </View>

    <View className='text-black text-opacity-40'>
      text-opacity-40
    </View>

    <View className='text-black text-opacity-50'>
      text-opacity-50
    </View>

    <View className='text-black text-opacity-60'>
      text-opacity-60
    </View>

    <View className='text-black text-opacity-70'>
      text-opacity-70
    </View>

    <View className='text-black text-opacity-80'>
      text-opacity-80
    </View>

    <View className='text-black text-opacity-90'>
      text-opacity-90
    </View>

    <View className='text-black text-opacity-100'>
      text-opacity-100
    </View>
  </View>
  )
}
