// examples/uniapp_vue3_postcss/src/pages/font/components/TextShadow.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      text-shadow
    </view>

    <view class="text-shadow">
      text-shadow
    </view>

    <view class="text-shadow-sm">
      text-shadow-sm
    </view>

    <view class="text-shadow-md">
      text-shadow-md
    </view>

    <view class="text-shadow-lg">
      text-shadow-lg
    </view>

    <view class="text-shadow-xl">
      text-shadow-xl
    </view>

    <view class="text-shadow-none">
      text-shadow-none
    </view>
  </view>
</template>

// examples/taro_webpack5_react/src/pages/font/components/TextShadow.tsx
import {View} from '@tarojs/components'

export default function TextShadow() {
  return (
    <View className='p-2'>
    <View className='text-2xl text-center my-3'>
      text-shadow
    </View>

    <View className='text-shadow'>
      text-shadow
    </View>

    <View className='text-shadow-sm'>
      text-shadow-sm
    </View>

    <View className='text-shadow-md'>
      text-shadow-md
    </View>

    <View className='text-shadow-lg'>
      text-shadow-lg
    </View>

    <View className='text-shadow-xl'>
      text-shadow-xl
    </View>

    <View className='text-shadow-none'>
      text-shadow-none
    </View>
  </View>
  )
}
