// examples/taro_vue3/src/pages/font/components/TextDecorationStyle.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      text-decoration-style
    </view>

    <view class="underline decoration-solid">
      underline decoration-solid
    </view>

    <view class="underline decoration-double">
      underline decoration-double
    </view>

    <view class="underline decoration-dotted">
      underline decoration-dotted
    </view>

    <view class="underline decoration-dashed">
      underline decoration-dashed
    </view>

    <view class="underline decoration-wavy">
      underline decoration-wavy
    </view>
  </view>
</template>

// examples/taro_webpack5_react/src/pages/font/components/TextDecorationStyle.tsx
import {View} from '@tarojs/components'

export default function TextDecorationStyle() {
  return (
    <View className='p-2'>
    <View className='text-2xl text-center my-3'>
      text-decoration-style
    </View>

    <View className='underline decoration-solid'>
      underline decoration-solid
    </View>

    <View className='underline decoration-double'>
      underline decoration-double
    </View>

    <View className='underline decoration-dotted'>
      underline decoration-dotted
    </View>

    <View className='underline decoration-dashed'>
      underline decoration-dashed
    </View>

    <View className='underline decoration-wavy'>
      underline decoration-wavy
    </View>
  </View>
  )
}
