// examples/taro_webpack4_vue3/src/pages/color/index.vue
<template>
  <view class="p-2 text-center">
    <view class="bg-[#34eeee] mb-1"> bg-[#3498db] </view>
    <view class="bg-[#3498db]/80 mb-1"> bg-[#3498db]/80 </view>

    <view class="bg-[#3498db]:60 mb-1"> bg-[#3498db]:60 </view>

    <view class="bg-[#3498db]_40 mb-1"> bg-[#3498db]_40 </view>

    <view class="bg-hex-e74c3c mb-1"> bg-hex-e74c3c </view>

    <view class="text-hex-8e44ad mb-1"> text-hex-8e44ad </view>

    <view class="text-hex-8e44ad/80 mb-1"> text-hex-8e44ad/80 </view>

    <view class="text-hex-8e44ad:60 mb-1"> text-hex-8e44ad:60 </view>

    <view class="text-hex-8e44ad_40 mb-1"> text-hex-8e44ad_40 </view>

    <view class="bg-hex-000/80 text-hex-fff:60 mb-1">
      bg-hex-000/80 text-hex-fff:60
    </view>
  </view>
</template>

// examples/taro_react/src/pages/color/index.tsx
export default function BorderColor() {
  return (
    <view className='p-2 text-center'>
    <view className='bg-[#3498db] mb-1'>
      bg-[#3498db]
    </view>
    <view className='bg-[#3498db]/80 mb-1'>
      bg-[#3498db]/80
    </view>

    <view className='bg-[#3498db]:60 mb-1'>
      bg-[#3498db]:60
    </view>

    <view className='bg-[#3498db]_40 mb-1'>
      bg-[#3498db]_40
    </view>

    <view className='bg-hex-e74c3c mb-1'>
      bg-hex-e74c3c
    </view>

    <view className='text-hex-8e44ad  mb-1'>
      text-hex-8e44ad
    </view>

    <view className='text-hex-8e44ad/80 mb-1'>
      text-hex-8e44ad/80
    </view>

    <view className='text-hex-8e44ad:60 mb-1'>
      text-hex-8e44ad:60
    </view>

    <view className='text-hex-8e44ad_40 mb-1'>
      text-hex-8e44ad_40
    </view>

    <view className='bg-hex-000/80 text-hex-fff:60 mb-1'>
      bg-hex-000/80 text-hex-fff:60
    </view>
  </view>
  )
}
