// examples/taro_react/src/pages/font/components/LineHeight.tsx


export default function LineHeight() {
  return (
    <view className='p-2'>
    <view className='text-2xl text-center my-3'>
      line-height
    </view>

    <view className='leading-none'>
      leading-none
    </view>

    <view className='leading-tight'>
      leading-tight
    </view>

    <view className='leading-snug'>
      leading-snug
    </view>

    <view className='leading-normal'>
      leading-normal
    </view>

    <view className='leading-relaxed'>
      leading-relaxed
    </view>

    <view className='leading-loose'>
      leading-loose
    </view>
  </view>
  )
}

// examples/taro_webpack4_vue3/src/pages/font/components/LineHeight.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      line-height
    </view>

    <view class="leading-none">
      leading-none
    </view>

    <view class="leading-tight">
      leading-tight
    </view>

    <view class="leading-snug">
      leading-snug
    </view>

    <view class="leading-normal">
      leading-normal
    </view>

    <view class="leading-relaxed">
      leading-relaxed
    </view>

    <view class="leading-loose">
      leading-loose
    </view>
  </view>
</template>
