// examples/taro_webpack5_react/src/pages/border/index.tsx

import BorderRadius from './components/BorderRadius'
import BorderWidth from './components/BorderWidth'
import BorderStyle from './components/BorderStyle'
import BorderColor from './components/BorderColor'
import {View} from '@tarojs/components'

export default function() {
  return (
    <View className='bg-white'>
    <BorderRadius />
    <BorderWidth />
    <BorderStyle />
    <BorderColor />
  </View>
  )
}

// examples/taro_webpack4_vue3/src/pages/border/index.vue
<script setup lang="ts">
import BorderRadius from './components/BorderRadius.vue'
import BorderWidth from './components/BorderWidth.vue'
import BorderStyle from './components/BorderStyle.vue'
import BorderColor from './components/BorderColor.vue'
</script>

<template>
  <view class="bg-white">
    <BorderRadius />
    <BorderWidth />
    <BorderStyle />
    <BorderColor />
  </view>
</template>
