// examples/uniapp_vue2/src/pages/border/components/BorderWidth.vue
<template>
  <view class="p-2">
    <view class="text-2xl text-center my-3">
      border-width
    </view>
    <view class="flex flex-col items-center">
      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-0">
        border-0
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border">
        border
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-base">
        border-base
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-2">
        border-2
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-4">
        border-4
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-6">
        border-6
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-8">
        border-8
      </view>

      <view class="w-half h-200 mb-3  bg-blue-100 center text-center border-10">
        border-10
      </view>
    </view>
  </view>
</template>

// examples/taro_webpack5_react/src/pages/border/components/BorderWidth.tsx
import {View} from '@tarojs/components'

export default function BorderWidth() {
  return (
    <View className='p-2'>
    <View className='text-2xl text-center my-3'>
      border-width
    </View>
    <View className='flex flex-col items-center'>
      <View className='w-half h-200 mb-3  bg-blue-100 center text-center border-0'>
        border-0
      </View>

      <View className='w-half h-200 mb-3  bg-blue-100 center text-center border'>
        border
      </View>

      <View className='w-half h-200 mb-3  bg-blue-100 center text-center border-base'>
        border-base
      </View>

      <View className='w-half h-200 mb-3  bg-blue-100 center text-center border-2'>
        border-2
      </View>

      <View className='w-half h-200 mb-3  bg-blue-100 center text-center border-4'>
        border-4
      </View>

      <View className='w-half h-200 mb-3  bg-blue-100 center text-center border-6'>
        border-6
      </View>

      <View className='w-half h-200 mb-3  bg-blue-100 center text-center border-8'>
        border-8
      </View>

      <View className='w-half h-200 mb-3  bg-blue-100 center text-center border-10'>
        border-10
      </View>
    </View>
  </View>
  )
}
