// examples/uniapp_vue3/src/pages/shortcuts/index.vue
<!--
 * @Author: licl
 * @Date: 2022-06-26 19:40:08
 * @LastEditTime: 2022-07-03 13:31:24
 * @LastEditors: licl
 * @Description:
-->

<template>
  <view class="flex flex-col items-center">
    <view class="w-300 h-300 bg-red-200 center my-3">
      center
    </view>

    <view class="w-300 h-300 bg-white border-base">
      border-base
    </view>
  </view>
</template>

<style lang="scss" scoped>

</style>

// examples/taro_webpack5_react/src/pages/shortcuts/index.tsx
import {View} from '@tarojs/components'

export default function() {
  return (
    <View className='flex flex-col items-center'>
    <View className='w-300 h-300 bg-red-200 center my-3'>
      center
    </View>

    <View className='w-300 h-300 bg-white border-base'>
      border-base
    </View>
  </View>
  )
}
